version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.8.0
    - 7.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.11
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby-source-contentful
    versions:
    - 4.5.1
  - dependency-name: lodash
    versions:
    - 4.17.20
